import type { IssueShape } from "../Utils/Shapes";

// Example goes here

export const Example_Issues_1: IssueShape[] = [
  {
    id: "1",
    name: "Interactive Calculus Workshop",
    status: "In Progress",
    description: "Develop and implement an interactive workshop series for advanced calculus concepts using real-world applications",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    progress: 50,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function"
  },
  {
    id: "2",
    name: "Mobile App Development",
    status: "Planning",
    description: "Create a cross-platform mobile application for task management with real-time synchronization",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-03-31"),
    progress: 15,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "3",
    name: "Machine Learning Model Training",
    status: "Completed",
    description: "Train and deploy a neural network for image recognition with 95% accuracy",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    progress: 100,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "4",
    name: "Website Redesign Project",
    status: "In Progress",
    description: "Complete overhaul of company website with modern UI/UX principles and responsive design",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    progress: 75,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "E-com"
  },
  {
    id: "5",
    name: "Data Migration Initiative",
    status: "On Hold",
    description: "Migrate legacy database systems to cloud-based infrastructure with zero downtime",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    progress: 25,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "6",
    name: "Customer Support Automation",
    status: "In Progress",
    description: "Implement AI-powered chatbot to handle 80% of customer inquiries automatically",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    progress: 60,
    vision: "Advance Capabilities",
    team: "Retail"
  },
  {
    id: "7",
    name: "Blockchain Integration",
    status: "Planning",
    description: "Integrate blockchain technology for secure transaction processing and data integrity",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-08-31"),
    progress: 5,
    vision: "Evolving Cyber Threats",
    team: "Tech"
  },
  {
    id: "8",
    name: "IoT Sensor Network",
    status: "In Progress",
    description: "Deploy Internet of Things sensors for real-time environmental monitoring",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    progress: 40,
    vision: "Awareness and Action",
    team: "Tech"
  },
  {
    id: "9",
    name: "Cybersecurity Audit",
    status: "Completed",
    description: "Comprehensive security assessment and vulnerability testing of all systems",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    progress: 100,
    vision: "Evolving Cyber Threats",
    team: "Tech"
  },
  {
    id: "10",
    name: "Virtual Reality Training Platform",
    status: "In Progress",
    description: "Develop immersive VR training modules for employee skill development",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    progress: 35,
    vision: "Advance Capabilities",
    team: "Function"
  },
  {
    id: "11",
    name: "API Gateway Implementation",
    status: "Testing",
    description: "Build and deploy centralized API gateway for microservices architecture",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    progress: 85,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "12",
    name: "Cloud Migration Strategy",
    status: "Planning",
    description: "Develop comprehensive strategy for migrating on-premise infrastructure to AWS",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    progress: 10,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "13",
    name: "User Authentication System",
    status: "In Progress",
    description: "Implement multi-factor authentication with biometric support",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    progress: 65,
    vision: "Evolving Cyber Threats",
    team: "Tech"
  },
  {
    id: "14",
    name: "Analytics Dashboard",
    status: "Completed",
    description: "Create real-time analytics dashboard with interactive visualizations",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    progress: 100,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "15",
    name: "Automated Testing Framework",
    status: "In Progress",
    description: "Develop comprehensive automated testing suite for continuous integration",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-04-30"),
    progress: 70,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "16",
    name: "Digital Twin Development",
    status: "Research",
    description: "Create digital twin models for predictive maintenance and optimization",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    progress: 5,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "17",
    name: "Supply Chain Optimization",
    status: "In Progress",
    description: "Implement AI-driven supply chain management for cost reduction and efficiency",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-06-30"),
    progress: 45,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Fulfillment"
  },
  {
    id: "18",
    name: "Microservices Architecture",
    status: "Planning",
    description: "Decompose monolithic application into scalable microservices",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    progress: 15,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "19",
    name: "Edge Computing Infrastructure",
    status: "In Progress",
    description: "Deploy edge computing nodes for reduced latency and improved performance",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    progress: 30,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "20",
    name: "Quantum Computing Research",
    status: "Research",
    description: "Explore quantum computing applications for complex optimization problems",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    progress: 8,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "21",
    name: "Green Energy Management",
    status: "In Progress",
    description: "Implement smart energy management system for renewable energy optimization",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-11-30"),
    progress: 55,
    vision: "Awareness and Action",
    team: "Corporate"
  },
  {
    id: "22",
    name: "Healthcare Data Platform",
    status: "Testing",
    description: "Develop HIPAA-compliant healthcare data analytics platform",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    progress: 90,
    vision: "Data Analysis",
    team: "Tech"
  },
  {
    id: "23",
    name: "Augmented Reality Interface",
    status: "In Progress",
    description: "Create AR interface for industrial maintenance and training applications",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    progress: 25,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "24",
    name: "Natural Language Processing",
    status: "Completed",
    description: "Deploy NLP system for automated document processing and analysis",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    progress: 100,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "25",
    name: "Robotic Process Automation",
    status: "In Progress",
    description: "Automate repetitive business processes using RPA technologies",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    progress: 50,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function"
  },
  {
    id: "26",
    name: "5G Network Integration",
    status: "Planning",
    description: "Integrate 5G connectivity for ultra-low latency applications",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    progress: 12,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "27",
    name: "Digital Identity Platform",
    status: "In Progress",
    description: "Build decentralized identity management system using blockchain",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    progress: 40,
    vision: "Evolving Cyber Threats",
    team: "Tech"
  },
  {
    id: "28",
    name: "Computer Vision System",
    status: "Testing",
    description: "Implement computer vision for quality control in manufacturing",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    progress: 80,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "29",
    name: "Smart City Infrastructure",
    status: "Research",
    description: "Design IoT-enabled smart city infrastructure for traffic and utilities",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    progress: 3,
    vision: "Awareness and Action",
    team: "Corporate"
  },
  {
    id: "30",
    name: "Predictive Analytics Engine",
    status: "In Progress",
    description: "Develop machine learning models for business forecasting and trend analysis",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    progress: 60,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "31",
    name: "Voice Recognition System",
    status: "Completed",
    description: "Implement multi-language voice recognition for accessibility features",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    progress: 100,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "32",
    name: "Distributed Database System",
    status: "In Progress",
    description: "Deploy distributed database with automatic sharding and replication",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    progress: 35,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "33",
    name: "Drone Delivery Network",
    status: "Planning",
    description: "Establish autonomous drone delivery system for last-mile logistics",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    progress: 8,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Fulfillment"
  },
  {
    id: "34",
    name: "Facial Recognition Security",
    status: "Testing",
    description: "Deploy facial recognition system for secure facility access control",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    progress: 85,
    vision: "Evolving Cyber Threats",
    team: "Tech"
  },
  {
    id: "35",
    name: "Environmental Monitoring",
    status: "In Progress",
    description: "Create comprehensive environmental monitoring system using satellite data",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    progress: 45,
    vision: "Awareness and Action",
    team: "Corporate"
  },
  {
    id: "36",
    name: "Automated Code Generation",
    status: "Research",
    description: "Develop AI system for automated code generation from natural language",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    progress: 15,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "37",
    name: "Smart Grid Integration",
    status: "In Progress",
    description: "Integrate renewable energy sources into intelligent power grid system",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    progress: 25,
    vision: "Awareness and Action",
    team: "Corporate"
  },
  {
    id: "38",
    name: "Biometric Payment System",
    status: "Planning",
    description: "Implement biometric-based payment system for enhanced security",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    progress: 10,
    vision: "Evolving Cyber Threats",
    team: "Tech"
  },
  {
    id: "39",
    name: "Real-time Translation",
    status: "In Progress",
    description: "Deploy real-time language translation system for global communication",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-06-30"),
    progress: 70,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "40",
    name: "Autonomous Vehicle Platform",
    status: "Research",
    description: "Develop autonomous vehicle control system with advanced AI algorithms",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    progress: 5,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "41",
    name: "Personalized Learning AI",
    status: "In Progress",
    description: "Create AI-powered personalized learning platform for adaptive education",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    progress: 55,
    vision: "Advance Capabilities",
    team: "Function"
  },
  {
    id: "42",
    name: "Digital Wallet Integration",
    status: "Testing",
    description: "Integrate multiple digital payment methods into unified wallet system",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    progress: 90,
    vision: "Evolving Cyber Threats",
    team: "Tech"
  },
  {
    id: "43",
    name: "Smart Manufacturing",
    status: "In Progress",
    description: "Implement Industry 4.0 technologies for intelligent manufacturing processes",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    progress: 30,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Product"
  },
  {
    id: "44",
    name: "Neural Interface Development",
    status: "Research",
    description: "Research brain-computer interfaces for assistive technologies",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    progress: 2,
    vision: "Data Analysis",
    team: "Tech"
  },
  {
    id: "45",
    name: "Climate Change Modeling",
    status: "In Progress",
    description: "Develop advanced climate models using supercomputing and AI",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    progress: 65,
    vision: "Awareness and Action",
    team: "Corporate"
  },
  {
    id: "46",
    name: "Holographic Display System",
    status: "Planning",
    description: "Create holographic display technology for immersive data visualization",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    progress: 7,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "47",
    name: "Space Communication Network",
    status: "Research",
    description: "Develop satellite-based communication network for global connectivity",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    progress: 1,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech"
  },
  {
    id: "48",
    name: "Gene Therapy Database",
    status: "In Progress",
    description: "Build secure database for gene therapy research and clinical trials",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    progress: 40,
    vision: "Data Analysis",
    team: "Tech"
  },
  {
    id: "49",
    name: "Emotion Recognition AI",
    status: "Testing",
    description: "Develop AI system for real-time emotion recognition and response",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    progress: 75,
    vision: "Advance Capabilities",
    team: "Tech"
  },
  {
    id: "50",
    name: "Underwater Exploration Robot",
    status: "In Progress",
    description: "Design autonomous underwater vehicle for deep-sea exploration and research",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    progress: 20,
    vision: "Awareness and Action",
    team: "Tech"
  },
];
