import type { IssueShape } from "../Utils/Shapes";

export const Example_Issues_2: IssueShape[] = [
  {
    id: "51",
    name: "AI-Powered Customer Service",
    status: "High Risks",
    description: "Implement AI chatbot for 24/7 customer support with natural language processing",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    progress: 65,
    category: "Revolutionize Customer Experience",
    team: "Tech",
    priority: "High"
  },
  {
    id: "52",
    name: "Sustainable Packaging Initiative",
    status: "Not Yet Started",
    description: "Develop and implement eco-friendly packaging solutions across all product lines",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    progress: 20,
    category: "The Consistancy of Axiom of Choice and General Continuum Hypothesis in the Context of Set Theory",
    team: "Product",
    priority: "High"
  },
  {
    id: "53",
    name: "Mobile App Redesign",
    status: "On Track",
    description: "Complete overhaul of mobile application with modern UI/UX principles",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    progress: 45,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "54",
    name: "Global Supply Chain Optimization",
    status: "Manageable Risk",
    description: "Implement AI-driven supply chain management system for global operations",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    progress: 30,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Fulfillment",
    priority: "Medium"
  },
  {
    id: "55",
    name: "Employee Training Platform",
    status: "On Track",
    description: "Launch comprehensive online learning platform for employee development",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    progress: 100,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Low"
  },
  {
    id: "56",
    name: "Data Security Enhancement",
    status: "High Risks",
    description: "Upgrade security infrastructure with advanced encryption and monitoring",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    progress: 75,
    category: "Evolving Cyber Threats",
    team: "Tech",
    priority: "Low"
  },
  {
    id: "57",
    name: "Retail Store Digitalization",
    status: "Not Yet Started",
    description: "Implement digital solutions in physical retail locations",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    progress: 100,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Retail",
    priority: "Low"
  },
  {
    id: "58",
    name: "E-commerce Platform Upgrade",
    status: "On Track",
    description: "Enhance online shopping experience with new features and improved performance",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    progress: 60,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "59",
    name: "Brand Identity Refresh",
    status: "Not Yet Started",
    description: "Update brand guidelines and visual identity across all channels",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    progress: 25,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "60",
    name: "Corporate Social Responsibility",
    status: "On Track",
    description: "Launch new CSR initiatives focused on community development",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    progress: 40,
    category: "Awareness and Action",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "61",
    name: "Product Innovation Lab",
    status: "Not Yet Started",
    description: "Establish dedicated space for product research and development",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    progress: 10,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "62",
    name: "Customer Analytics Platform",
    status: "On Track",
    description: "Develop advanced analytics system for customer behavior insights",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    progress: 55,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "63",
    name: "Global Market Expansion",
    status: "Not Yet Started",
    description: "Develop strategy for entering new international markets",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    progress: 20,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "64",
    name: "Smart Inventory System",
    status: "On Track",
    description: "Implement AI-powered inventory management system",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    progress: 70,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Fulfillment",
    priority: "Medium"
  },
  {
    id: "65",
    name: "Digital Marketing Campaign",
    status: "Not Yet Started",
    description: "Launch comprehensive digital marketing strategy",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    progress: 35,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "66",
    name: "Employee Wellness Program",
    status: "On Track",
    description: "Implement comprehensive employee wellness initiatives",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    progress: 45,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "67",
    name: "Store Experience Redesign",
    status: "Not Yet Started",
    description: "Redesign physical store layout and customer experience",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    progress: 100,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "68",
    name: "Cloud Infrastructure Migration",
    status: "High Risks",
    description: "Migrate legacy systems to cloud-based infrastructure",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-06-30"),
    progress: 60,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "69",
    name: "Product Quality Enhancement",
    status: "Not Yet Started",
    description: "Implement new quality control measures across product lines",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    progress: 25,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "70",
    name: "E-commerce Analytics Dashboard",
    status: "On Track",
    description: "Develop real-time analytics dashboard for e-commerce operations",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    progress: 50,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "71",
    name: "Corporate Sustainability Goals",
    status: "Not Yet Started",
    description: "Set and implement new corporate sustainability targets",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    progress: 30,
    category: "Awareness and Action",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "72",
    name: "Employee Training Program",
    status: "On Track",
    description: "Launch new employee training and development program",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    progress: 40,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "73",
    name: "Retail Technology Integration",
    status: "Not Yet Started",
    description: "Integrate new technologies into retail operations",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    progress: 20,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "74",
    name: "Brand Awareness Campaign",
    status: "On Track",
    description: "Launch global brand awareness campaign",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    progress: 35,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "75",
    name: "Supply Chain Visibility",
    status: "Not Yet Started",
    description: "Implement end-to-end supply chain visibility platform",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    progress: 25,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Fulfillment",
    priority: "Medium"
  },
  {
    id: "76",
    name: "AI Product Recommendations",
    status: "On Track",
    description: "Develop AI-powered product recommendation engine",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    progress: 55,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "77",
    name: "Store Performance Metrics",
    status: "Not Yet Started",
    description: "Implement comprehensive store performance tracking system",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    progress: 30,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "78",
    name: "E-commerce Mobile App",
    status: "On Track",
    description: "Develop new mobile shopping application",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    progress: 65,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "79",
    name: "Brand Voice Guidelines",
    status: "Not Yet Started",
    description: "Create comprehensive brand voice and tone guidelines",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    progress: 40,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "80",
    name: "Corporate Ethics Program",
    status: "On Track",
    description: "Develop and implement corporate ethics training program",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    progress: 45,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "81",
    name: "Product Design System",
    status: "Not Yet Started",
    description: "Create unified product design system",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    progress: 35,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "82",
    name: "HR Management System",
    status: "On Track",
    description: "Implement new HR management platform",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    progress: 60,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "83",
    name: "Retail Analytics Dashboard",
    status: "Not Yet Started",
    description: "Develop comprehensive retail analytics dashboard",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    progress: 25,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "84",
    name: "Cloud Security Framework",
    status: "High Risks",
    description: "Implement cloud security best practices",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    progress: 70,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "85",
    name: "E-commerce Checkout Optimization",
    status: "Not Yet Started",
    description: "Optimize online checkout process",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    progress: 30,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "86",
    name: "Brand Content Strategy",
    status: "On Track",
    description: "Develop comprehensive content strategy",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    progress: 50,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "87",
    name: "Corporate Risk Management",
    status: "Not Yet Started",
    description: "Implement enterprise risk management framework",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    progress: 35,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "88",
    name: "Product Quality Assurance",
    status: "On Track",
    description: "Enhance product quality assurance processes",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    progress: 55,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "89",
    name: "Employee Performance System",
    status: "Not Yet Started",
    description: "Implement new performance management system",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    progress: 40,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "90",
    name: "Store Operations Platform",
    status: "On Track",
    description: "Develop comprehensive store operations platform",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    progress: 65,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "91",
    name: "API Security Enhancement",
    status: "High Risks",
    description: "Implement advanced API security measures",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    progress: 45,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "92",
    name: "E-commerce Search Optimization",
    status: "On Track",
    description: "Enhance product search functionality",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-06-30"),
    progress: 50,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "93",
    name: "Brand Experience Platform",
    status: "Not Yet Started",
    description: "Develop unified brand experience platform",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    progress: 30,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "94",
    name: "Corporate Compliance System",
    status: "On Track",
    description: "Implement comprehensive compliance management system",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    progress: 60,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "95",
    name: "Product Innovation Process",
    status: "Not Yet Started",
    description: "Develop structured product innovation framework",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    progress: 35,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "96",
    name: "HR Analytics Platform",
    status: "On Track",
    description: "Implement HR analytics and reporting system",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    progress: 55,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "97",
    name: "Retail Customer Insights",
    status: "Not Yet Started",
    description: "Develop customer insights platform for retail",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    progress: 40,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "98",
    name: "Cloud Migration Strategy",
    status: "On Track",
    description: "Develop comprehensive cloud migration plan",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    progress: 45,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "99",
    name: "E-commerce Payment System",
    status: "Not Yet Started",
    description: "Implement new payment processing system",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    progress: 30,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "100",
    name: "Brand Strategy Refresh",
    status: "On Track",
    description: "Update and implement new brand strategy",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    progress: 50,
    category: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  }
]; 