import type { IssueShape } from "../Utils/Shapes";

export const Example_Issues_3: IssueShape[] = [
  {
    id: "101",
    name: "Smart Fitting Room Technology",
    status: "Risk in control",
    description: "Implement AI-powered smart mirrors in fitting rooms for enhanced customer experience",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-03-31"),
    progress: 70,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "102",
    name: "Sustainable Material Sourcing",
    status: "Planning",
    description: "Develop sustainable material sourcing strategy for all product lines",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    progress: 25,
    vision: "The Consistancy of Axiom of Choice and General Continuum Hypothesis in the Context of Set Theory",
    team: "Product",
    priority: "Low"
  },
  {
    id: "103",
    name: "Omnichannel Integration",
    status: "In Progress",
    description: "Seamlessly integrate online and offline shopping experiences",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-05-31"),
    progress: 55,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "E-com",
    priority: "Low"
  },
  {
    id: "104",
    name: "Inventory Forecasting System",
    status: "On Hold",
    description: "Implement AI-based inventory forecasting for optimized stock levels",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    progress: 35,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Fulfillment",
    priority: "Medium"
  },
  {
    id: "105",
    name: "Leadership Development Program",
    status: "Completed",
    description: "Launch comprehensive leadership training program for managers",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    progress: 100,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "106",
    name: "Cybersecurity Framework",
    status: "Risk in control",
    description: "Implement comprehensive cybersecurity framework across all systems",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-08-31"),
    progress: 80,
    vision: "Evolving Cyber Threats",
    team: "Tech",
    priority: "High"
  },
  {
    id: "107",
    name: "Store Layout Optimization",
    status: "Planning",
    description: "Optimize store layouts based on customer behavior analytics",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    progress: 20,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Retail",
    priority: "High"
  },
  {
    id: "108",
    name: "Mobile Payment Integration",
    status: "In Progress",
    description: "Implement new mobile payment solutions across all channels",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-10-31"),
    progress: 65,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "E-com",
    priority: "High"
  },
  {
    id: "109",
    name: "Social Media Strategy",
    status: "Planning",
    description: "Develop comprehensive social media marketing strategy",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    progress: 30,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "110",
    name: "Diversity and Inclusion",
    status: "In Progress",
    description: "Launch new diversity and inclusion initiatives across the organization",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    progress: 45,
    vision: "Awareness and Action",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "111",
    name: "Product Testing Lab",
    status: "Research",
    description: "Establish advanced product testing facility",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    progress: 15,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "112",
    name: "Customer Journey Analytics",
    status: "Risk in control",
    description: "Implement advanced analytics for customer journey mapping",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2025-02-28"),
    progress: 60,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "113",
    name: "International Market Research",
    status: "Planning",
    description: "Conduct comprehensive research for new market entry",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    progress: 25,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "114",
    name: "Warehouse Automation",
    status: "In Progress",
    description: "Implement automated warehouse management system",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-04-30"),
    progress: 75,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Fulfillment",
    priority: "Medium"
  },
  {
    id: "115",
    name: "Influencer Marketing Program",
    status: "Planning",
    description: "Launch strategic influencer marketing campaign",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    progress: 40,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "116",
    name: "Employee Engagement Platform",
    status: "In Progress",
    description: "Develop new employee engagement and feedback system",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    progress: 50,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "117",
    name: "Store Performance Analytics",
    status: "Planning",
    description: "Implement advanced analytics for store performance tracking",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    progress: 20,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "118",
    name: "API Gateway Development",
    status: "In Progress",
    description: "Build centralized API gateway for microservices",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-08-31"),
    progress: 65,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "119",
    name: "Product Lifecycle Management",
    status: "Planning",
    description: "Implement comprehensive product lifecycle management system",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    progress: 30,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "120",
    name: "E-commerce Personalization",
    status: "In Progress",
    description: "Implement AI-driven personalization for online shopping",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-10-31"),
    progress: 55,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "121",
    name: "Corporate Governance Review",
    status: "Planning",
    description: "Conduct comprehensive review of corporate governance framework",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    progress: 35,
    vision: "Awareness and Action",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "122",
    name: "Skills Development Program",
    status: "In Progress",
    description: "Launch new skills development initiative for employees",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    progress: 45,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "123",
    name: "Retail Analytics Platform",
    status: "Planning",
    description: "Develop advanced analytics platform for retail operations",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    progress: 25,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "124",
    name: "Brand Experience Design",
    status: "In Progress",
    description: "Create immersive brand experience across all touchpoints",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    progress: 40,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "125",
    name: "Supply Chain Optimization",
    status: "Planning",
    description: "Implement advanced supply chain optimization algorithms",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    progress: 30,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Fulfillment",
    priority: "Medium"
  },
  {
    id: "126",
    name: "AI Customer Insights",
    status: "In Progress",
    description: "Develop AI-powered customer behavior analysis system",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-04-30"),
    progress: 60,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "127",
    name: "Store Digital Transformation",
    status: "Planning",
    description: "Implement comprehensive digital transformation in retail stores",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    progress: 35,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "128",
    name: "E-commerce Platform Enhancement",
    status: "In Progress",
    description: "Enhance e-commerce platform with advanced features",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-06-30"),
    progress: 70,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "129",
    name: "Brand Identity Evolution",
    status: "Planning",
    description: "Evolve brand identity for modern market demands",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    progress: 45,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "130",
    name: "Corporate Strategy Refresh",
    status: "In Progress",
    description: "Update corporate strategy for new market conditions",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    progress: 50,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "131",
    name: "Product Innovation Hub",
    status: "Planning",
    description: "Establish innovation hub for product development",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    progress: 25,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "132",
    name: "HR Digital Transformation",
    status: "In Progress",
    description: "Implement digital HR management solutions",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    progress: 55,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "133",
    name: "Retail Experience Platform",
    status: "Planning",
    description: "Develop unified retail experience platform",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    progress: 40,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "134",
    name: "Cloud Security Enhancement",
    status: "Risk in control",
    description: "Enhance cloud security infrastructure",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-12-31"),
    progress: 65,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "135",
    name: "E-commerce Analytics Platform",
    status: "Planning",
    description: "Develop comprehensive e-commerce analytics platform",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    progress: 35,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "136",
    name: "Brand Engagement Strategy",
    status: "In Progress",
    description: "Develop new brand engagement strategy",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    progress: 45,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "137",
    name: "Corporate Innovation Lab",
    status: "Planning",
    description: "Establish corporate innovation laboratory",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    progress: 30,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "138",
    name: "Product Quality System",
    status: "In Progress",
    description: "Implement comprehensive product quality management system",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-04-30"),
    progress: 60,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "139",
    name: "Employee Development Platform",
    status: "Planning",
    description: "Develop employee development and training platform",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    progress: 40,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "140",
    name: "Store Operations System",
    status: "In Progress",
    description: "Implement advanced store operations management system",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    progress: 55,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "141",
    name: "API Development Framework",
    status: "Planning",
    description: "Create standardized API development framework",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    progress: 35,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "142",
    name: "E-commerce Platform Security",
    status: "In Progress",
    description: "Enhance e-commerce platform security measures",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-08-31"),
    progress: 50,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "143",
    name: "Brand Strategy Platform",
    status: "Planning",
    description: "Develop comprehensive brand strategy platform",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    progress: 45,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  },
  {
    id: "144",
    name: "Corporate Risk Framework",
    status: "In Progress",
    description: "Implement enterprise risk management framework",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    progress: 40,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Corporate",
    priority: "Medium"
  },
  {
    id: "145",
    name: "Product Development System",
    status: "Planning",
    description: "Implement new product development management system",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    progress: 35,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Product",
    priority: "Medium"
  },
  {
    id: "146",
    name: "HR Analytics System",
    status: "In Progress",
    description: "Develop comprehensive HR analytics platform",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    progress: 55,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Function",
    priority: "Medium"
  },
  {
    id: "147",
    name: "Retail Intelligence Platform",
    status: "Planning",
    description: "Develop retail intelligence and analytics platform",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    progress: 30,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Retail",
    priority: "Medium"
  },
  {
    id: "148",
    name: "Cloud Infrastructure Upgrade",
    status: "Risk in control",
    description: "Upgrade cloud infrastructure for improved performance",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2026-02-28"),
    progress: 65,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "Tech",
    priority: "Medium"
  },
  {
    id: "149",
    name: "E-commerce Experience Platform",
    status: "Planning",
    description: "Develop unified e-commerce experience platform",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    progress: 40,
    vision: "To revolutionize retail experience through innovative technology.",
    team: "E-com",
    priority: "Medium"
  },
  {
    id: "150",
    name: "Brand Innovation Lab",
    status: "In Progress",
    description: "Establish brand innovation laboratory",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    progress: 45,
    vision: "To revolutionize personal productivity through intuitive mobile solutions.",
    team: "Brand Marketing",
    priority: "Medium"
  }
]; 